server:
  port: 1667


# ------------------------------------------------------------------------------
# actuarot
# ------------------------------------------------------------------------------
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"





